//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC_Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compania_Tipo_Contacto
    {
        public int Consecutivo { get; set; }
        public string id { get; set; }
        public string CompaniaId { get; set; }
        public string Tipo_ContactoId { get; set; }
        public string Valor { get; set; }
    
        public virtual Compania Compania { get; set; }
        public virtual Tipo_Contacto Tipo_Contacto { get; set; }
    }
}
