//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC_Falabella.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contexto_Datos : DbContext
    {
        public Contexto_Datos()
            : base("name=Contexto_Datos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad> Actividad { get; set; }
        public virtual DbSet<Asesor> Asesor { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Compania> Compania { get; set; }
        public virtual DbSet<Compania_Tipo_Contacto> Compania_Tipo_Contacto { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Producto_Actividad> Producto_Actividad { get; set; }
        public virtual DbSet<Tipo_Contacto> Tipo_Contacto { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
        public virtual DbSet<Tipo_Producto> Tipo_Producto { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<Venta_Producto> Venta_Producto { get; set; }
    }
}
