//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC_Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Producto_Actividad = new HashSet<Producto_Actividad>();
            this.Venta_Producto = new HashSet<Venta_Producto>();
        }
    
        public int Consecutivo { get; set; }
        public string id { get; set; }
        public string Nombre { get; set; }
        public string Tipo_ProductoId { get; set; }
        public string CompaniaId { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Compania Compania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Actividad> Producto_Actividad { get; set; }
        public virtual Tipo_Producto Tipo_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Producto> Venta_Producto { get; set; }
    }
}
