//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC_Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Actividad
    {
        public int Consecutivo { get; set; }
        public string id { get; set; }
        public string ProductoId { get; set; }
        public string ActividadId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
