//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC_Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Venta_Producto = new HashSet<Venta_Producto>();
        }
    
        public int Consecutivo { get; set; }
        public string id { get; set; }
        public string AsesorId { get; set; }
        public string ClienteId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Asesor Asesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Producto> Venta_Producto { get; set; }
        public virtual Cliente Cliente { get; set; }

        public List<Venta_Producto> Lista_Productos { get; set; }


    }
}
